services:
  bookify-frontend:
    image: keesreukers23/bookify-frontend
    container_name: bookify-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"  
    depends_on:
      - bookify-backend 
    
  bookify-frontend2:
    image: keesreukers23/bookify-frontend2
    container_name: bookify-frontend2
    build:
      context: ./frontend2
    ports:
      - "3001:3000" 
    depends_on:
      - bookify-backend   
    
  bookify-backend:
    image: keesreukers23/bookify-backend
    container_name: bookify-backend
    build:
      context: ./backend  
      dockerfile: bookify/Dockerfile 
    ports:
      - "5169:8080" 
    environment:
      - ASPNETCORE_URLS=http://+:8080  
      - ConnectionStrings__Bookify=Server=mssqlstud.fhict.local;Database=dbi368833_bookify;User Id=dbi368833_bookify;Password=Fretvlemnup3;TrustServerCertificate=true;
      - JwtSettings__SecretKey=TzYwYk91NkxmVDNhNkczZVRHQXRTY3JpWXRONjNNSXg=
      - JwtSettings__Issuer=BookifyAPI
      - JwtSettings__Audience=BookifyClient
 
