name: .NET and React CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test backend/Bookify.Tests/Bookify.Tests.csproj --no-build --verbosity normal

    - name: Build Docker image for backend
      run: |
        docker build -t keesreukers23/bookify-backend ./backend/bookify

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image for backend
      run: |
        docker push keesreukers23/bookify-backend:latest 
    
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x' 

    - name: Install dependencies
      run: |
        cd frontend  
        npm install

    - name: Build React app
      run: |
        cd frontend  
        npm run build

    - name: Build Docker image for frontend
      run: |
        docker build -t bookify-frontend ./frontend

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Push Docker image for frontend 
      run: |
        docker tag bookify-frontend keesreukers23/bookify-frontend:latest
        docker push keesreukers23/bookify-frontend:latest
  
  build_frontend2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x' 
    - name: Install dependencies for frontend2
      run: |
        cd frontend2
        npm install
    - name: Build React app for frontend2
      run: |
        cd frontend2
        npm run build

    - name: Build Docker image for frontend2
      run: |
        docker build -t keesreukers23/bookify-frontend2 ./frontend2
        
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image for frontend2
      run: |
        docker push keesreukers23/bookify-frontend2:latest


  deploy:
    runs-on: ubuntu-latest
    needs: [build_backend, build_frontend, build_frontend2]  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
      
    - name: Clean up old Docker images
      run: |
        docker system prune -f

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Verify Docker containers are running
      run: |
        docker ps

