name: .NET and React CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Backend build
  build_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run tests
      run: dotnet test Bookify.Tests/Bookify.Tests.csproj --no-build --verbosity normal
      working-directory: backend 

  # Backend deploy
  deploy_backend:
    runs-on: ubuntu-latest
    needs: [build_backend, test_backend]
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      working-directory: ./backend
      run: |
        docker build -f ./bookify/Dockerfile -t keesreukers23/bookify-backend .
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: |
        docker push keesreukers23/bookify-backend:latest

  # Frontend build
  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        cd frontend  
        npm install
    - name: Build React app
      run: |
        cd frontend  
        npm run build

  # Frontend deploy
  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build -t bookify-frontend ./frontend
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: |
        docker tag bookify-frontend keesreukers23/bookify-frontend:latest
        docker push keesreukers23/bookify-frontend:latest

  # Frontend2 build
  build_frontend2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        cd frontend2
        npm install
    - name: Build React app
      run: |
        cd frontend2
        npm run build

  # Frontend2 deploy
  deploy_frontend2:
    runs-on: ubuntu-latest
    needs: build_frontend2
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build -t keesreukers23/bookify-frontend2 ./frontend2
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: |
        docker push keesreukers23/bookify-frontend2:latest
