name: .NET and React CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Backend Build Job
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

  # Backend Test Job
  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Test
        run: dotnet test backend/Bookify.Tests/Bookify.Tests.csproj --no-build --verbosity normal

  # Backend Deploy Job
  deploy-backend:
    runs-on: ubuntu-latest
    needs: [test-backend]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image for backend
        working-directory: ./backend
        run: |
          docker build -f ./bookify/Dockerfile -t keesreukers23/bookify-backend .
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image for backend
        run: |
          docker push keesreukers23/bookify-backend:latest

  # Frontend Build Job
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Build React app
        run: |
          cd frontend
          npm run build

  # Frontend Deploy Job
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image for frontend
        run: |
          docker build -t bookify-frontend ./frontend
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image for frontend
        run: |
          docker tag bookify-frontend keesreukers23/bookify-frontend:latest
          docker push keesreukers23/bookify-frontend:latest
